# Generated by Django 4.1.4 on 2023-03-15 23:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='inactive', max_length=14, verbose_name='Status')),
                ('name', models.CharField(db_index=True, default='', max_length=14, verbose_name='Name')),
                ('category', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('bagel', 'Bagel')], db_index=True, default='others', max_length=14, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
